server:
  port: 8080
logging:
  pattern:
    console: "[%d{HH:mm:ss.SSS}] [%thread] [%highlight(%-5level)] [%logger{36}.%method\\(\\)] [%msg]%n"

custom:
  message: Hello World
  user-proxy-url: http://localhost:${server.port}/users
